"""Type stubs for aiosqlite."""

from __future__ import annotations

import sqlite3
from typing import Any, Optional

class Error(Exception): ...
class IntegrityError(Error): ...
class Warning(Exception): ...

class Connection:
    row_factory: Any
    async def execute(self, sql: str, parameters: Any = ...) -> Cursor: ...
    async def executemany(self, sql: str, parameters: Any = ...) -> Cursor: ...
    async def executescript(self, sql: str) -> Cursor: ...
    async def fetchone(self) -> Any: ...
    async def fetchall(self) -> list[Any]: ...
    async def fetchmany(self, size: int = ...) -> list[Any]: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def close(self) -> None: ...
    async def execute_insert(self, sql: str, parameters: Any = ...) -> int: ...
    async def execute_fetchall(self, sql: str, parameters: Any = ...) -> list[Any]: ...
    def cursor(self) -> Cursor: ...
    async def __aenter__(self) -> Connection: ...
    async def __aexit__(self, *args: Any) -> None: ...

class Cursor:
    row_factory: Any
    async def execute(self, sql: str, parameters: Any = ...) -> Cursor: ...
    async def executemany(self, sql: str, parameters: Any = ...) -> Cursor: ...
    async def fetchone(self) -> Any: ...
    async def fetchall(self) -> list[Any]: ...
    async def fetchmany(self, size: int = ...) -> list[Any]: ...
    @property
    def lastrowid(self) -> int: ...
    @property
    def rowcount(self) -> int: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> Cursor: ...
    async def __aexit__(self, *args: Any) -> None: ...

class Row:
    def __getitem__(self, key: str | int) -> Any: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Any: ...
    def keys(self) -> list[str]: ...

async def connect(
    database: str = ...,
    *,
    timeout: float = ...,
    detect_types: int = ...,
    isolation_level: str | None = ...,
    check_same_thread: bool = ...,
    cached_statements: int = ...,
    uri: bool = ...,
) -> Connection: ...

STMT_WRITERS: int
STMT_READERS: int
STMT_ALL: int
